// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_PpcIuD8o0-snJqh5Ti8mDg2WgywwUIo',
    appId: '1:110748370348:web:4c811e83a4e36eba512609',
    messagingSenderId: '110748370348',
    projectId: 'family-wallet-4521b',
    authDomain: 'family-wallet-4521b.firebaseapp.com',
    storageBucket: 'family-wallet-4521b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHwJwUzXgchqRl93Zc9eDVSGm1aB2USg',
    appId: '1:110748370348:android:eb5249055a0c87b7512609',
    messagingSenderId: '110748370348',
    projectId: 'family-wallet-4521b',
    storageBucket: 'family-wallet-4521b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6FoMyoYP7e9CkfviKTdZ7Q4OYzeCQKdU',
    appId: '1:110748370348:ios:6ec309f27e69e2ac512609',
    messagingSenderId: '110748370348',
    projectId: 'family-wallet-4521b',
    storageBucket: 'family-wallet-4521b.firebasestorage.app',
    iosBundleId: 'com.example.familyWalletChildren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6FoMyoYP7e9CkfviKTdZ7Q4OYzeCQKdU',
    appId: '1:110748370348:ios:6ec309f27e69e2ac512609',
    messagingSenderId: '110748370348',
    projectId: 'family-wallet-4521b',
    storageBucket: 'family-wallet-4521b.firebasestorage.app',
    iosBundleId: 'com.example.familyWalletChildren',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_PpcIuD8o0-snJqh5Ti8mDg2WgywwUIo',
    appId: '1:110748370348:web:09e82332e9e239aa512609',
    messagingSenderId: '110748370348',
    projectId: 'family-wallet-4521b',
    authDomain: 'family-wallet-4521b.firebaseapp.com',
    storageBucket: 'family-wallet-4521b.firebasestorage.app',
  );
}
